---
name: JSON

"on":
  push:
    branches:
      - main
    paths:
      - ".github/workflows/json.yml"
      - "**.json"
  pull_request:
    paths:
      - ".github/workflows/json.yml"
      - "**.json"

jobs:
  style:
    name: Style
    uses: jdno/workflows/.github/workflows/json-style.yml@main
