---
name: Shell

"on":
  push:
    branches:
      - main
    paths:
      - ".github/workflows/shell.yml"
      - "**.sh"
  pull_request:
    paths:
      - ".github/workflows/shell.yml"
      - "**.sh"

jobs:
  lint:
    name: Lint
    uses: jdno/workflows/.github/workflows/shell-lint.yml@main

  style:
    name: Style
    uses: jdno/workflows/.github/workflows/shell-style.yml@main
