---
name: TypeScript

"on":
  push:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
      - "**.ts"
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"
      - "**.ts"

jobs:
  lint:
    name: Lint
    uses: jdno/workflows/.github/workflows/typescript-lint.yml

  style:
    name: Style
    uses: jdno/workflows/.github/workflows/typescript-style.yml

  test:
    name: Test
    uses: jdno/workflows/.github/workflows/typescript-test.yml
