---
name: YAML

"on":
  push:
    branches:
      - main
    paths:
      - ".github/workflows/yaml.yml"
      - "**.yml"
      - "**.yaml"
  pull_request:
    paths:
      - ".github/workflows/yaml.yml"
      - "**.yml"
      - "**.yaml"

jobs:
  lint:
    name: Lint
    uses: jdno/workflows/.github/workflows/yaml-lint.yml@main

  style:
    name: Style
    uses: jdno/workflows/.github/workflows/yaml-style.yml@main
